//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftwareBDEntities : DbContext
    {
        public SoftwareBDEntities()
            : base("name=SoftwareBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_asistencia> tb_asistencia { get; set; }
        public virtual DbSet<tb_aula> tb_aula { get; set; }
        public virtual DbSet<tb_auxiliar> tb_auxiliar { get; set; }
        public virtual DbSet<tb_clase> tb_clase { get; set; }
        public virtual DbSet<tb_inventario> tb_inventario { get; set; }
        public virtual DbSet<tb_materia> tb_materia { get; set; }
        public virtual DbSet<tb_monitor> tb_monitor { get; set; }
        public virtual DbSet<tb_persona> tb_persona { get; set; }
        public virtual DbSet<tb_profesor> tb_profesor { get; set; }
        public virtual DbSet<tb_programa> tb_programa { get; set; }
        public virtual DbSet<tb_reserva> tb_reserva { get; set; }
        public virtual DbSet<tb_tipoelemento> tb_tipoelemento { get; set; }
    }
}
